---
# roles/nvim_packer/molecule/default/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubi9
    image: quay.io/maartenq/ansible-molecule-ubi9
    groups:
      - ansible
    override_command: false
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true

  - name: archlinux
    image: quay.io/maartenq/ansible-molecule-archlinux
    groups:
      - ansible
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true

  - name: fedora
    image: quay.io/maartenq/ansible-molecule-fedora
    groups:
      - ansible
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
  inventory:
    group_vars:
      ansible:
        ansible_user: ansible
verifier:
  name: ansible

scenario:
  test_sequence:
    # - dependency
    # - lint
    # - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy
