---
- name: Prepare
  hosts: all
  vars:
    platform:
      Darwin:
        become: false
  tasks:
    - name: Install latest archlinux-keyring
      become: true
      community.general.pacman:
        name: archlinux-keyring
      when:
        - ansible_os_family == "Archlinux"

    - name: Full system upgrade
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
      when:
        - ansible_os_family == "Archlinux"

    - name: Ensure Git is installed
      become: "{{ platform[ansible_facts.os_family].become | default(True) }}"
      ansible.builtin.package:
        name: git
        state: present
