---
# galaxy.yml
# vim: ai et ts=2 sw=2 sts=2 ft=yaml fenc=UTF-8

namespace: maartenq
name: config
version: 0.0.5
readme: README.md
authors:
  - maartenq
description: Ansible Collection for different config related stuff.
license:
  - MIT
tags:
  - tools
  - configuration
dependencies: {}
repository: https://github.com/maartenq/ansible-collection-config
documentation: https://github.com/maartenq/ansible-collection-config.git
homepage: https://github.com/maartenq/ansible-collection-config.git
issues: https://github.com/maartenq/ansible-collection-config/issues
build_ignore:
  - .github
  - .gitignore
  - .pre-commit-config.yaml
  - ansible.cfg
  - galaxy-deploy.yml
