---
# roles/nvim_packer/tasks/main.yml

- name: Set xgd_data_home from environment or fall back on default.
  ansible.builtin.set_fact:
    xgd_data_home: >-
      {{
        ansible_env.XDG_DATA_HOME
        | default(ansible_env.HOME + "/.local/share")
      }}

- name: Ensure XGD_DATA_HOME directory is created.
  ansible.builtin.file:
    path: "{{ xgd_data_home }}"
    state: directory
    mode: "{{ platform[ansible_os_family].user_dir_mode }}"

- name: Install nvim packer from Git repo.
  ansible.builtin.git:
    repo: "{{ nvim_packer_repo_url }}"
    dest: "{{ xgd_data_home }}/nvim/site/pack/packer/start/packer.nvim"
    update: "{{ nvim_packer_update | bool }}"
    depth: 1
    version: "{{ nvim_packer_version }}"
